# Generated by Django 3.1.6 on 2021-02-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutUs')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=11)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ourAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('matric_marksheet', models.FileField(upload_to='')),
                ('twelth_marksheet', models.FileField(upload_to='')),
                ('adhar_card', models.FileField(upload_to='')),
                ('passport_size_photo', models.ImageField(upload_to='registered_user')),
                ('transfer_certificate', models.FileField(upload_to='')),
                ('migration_certificate', models.FileField(upload_to='')),
                ('jee_mains', models.FileField(upload_to='')),
            ],
        ),
    ]
