# Generated by Django 3.1.6 on 2021-02-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerserviceapp', '0004_auto_20210206_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='adhar_card',
            field=models.FileField(upload_to='registered_user'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='jee_mains',
            field=models.FileField(upload_to='registered_user'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='matric_marksheet',
            field=models.FileField(upload_to='registered_user'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='migration_certificate',
            field=models.FileField(upload_to='registered_user'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transfer_certificate',
            field=models.FileField(upload_to='registered_user'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='twelth_marksheet',
            field=models.FileField(upload_to='registered_user'),
        ),
    ]
