# Generated by Django 3.1.6 on 2021-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerserviceapp', '0005_auto_20210206_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
