# Generated by Django 3.1.6 on 2021-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerserviceapp', '0006_auto_20210209_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_num', models.CharField(max_length=50)),
                ('gmail', models.CharField(max_length=50)),
            ],
        ),
    ]
