# Generated by Django 3.1.6 on 2021-02-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerserviceapp', '0007_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=200)),
            ],
        ),
    ]
