# Generated by Django 3.1.6 on 2021-02-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerserviceapp', '0008_maintext'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeWithUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='college_us')),
                ('link', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
